[package]
name = "public"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
serde_yml = "0.0.10"
hmac = "0.12.1"
sha2 = "0.10.8"
hex = "0.4.3"